FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.8-bullseye as python

# Customized first-run-notice to give clues how to work with this devcontainer.
COPY .devcontainer/first-run-notice.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt
